In [5]:
import numpy as np

In [1]:
from sklearn.datasets import fetch_openml

In [2]:
mnist = fetch_openml('mnist_784')

In [3]:
X = mnist.data

In [9]:
y_odd = np.int32(np.int32(mnist.target) % 2 == 1)
y_odd[:5]

array([1, 0, 0, 1, 1])

In [10]:
y_large = np.int32(np.int32(mnist.target) >=7)
y_large[:5]

array([0, 0, 0, 0, 1])

In [11]:
y_odd_large = np.c_[y_odd, y_large]

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
knn = KNeighborsClassifier(n_neighbors = 10)

In [22]:
knn.fit(X, y_odd_large)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=10, p=2,
           weights='uniform')

In [23]:
knn.predict(X[:5])

array([[1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1]])

In [24]:
mnist.target[:5]

array(['5', '0', '4', '1', '9'], dtype=object)