In [54]:
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
class MyLinearRegression(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass
    def fit(self, X, y):
        m,n = X.shape
        X_b = np.c_[np.ones((m,1)), X]
        self.theta_hat = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
        self.intercept_ = self.theta_hat[0]
        self.coef_ = self.theta_hat[1:]
        return self
    def predict(self, X ,y=None):
        m,n = X.shape
        X_b = np.c_[np.ones((m,1)), X]
        return X_b.dot(self.theta_hat)

In [55]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

In [56]:
my_lin_reg = MyLinearRegression()
my_lin_reg.fit(housing.data,housing.target.reshape(-1,1))

MyLinearRegression()

In [57]:
my_lin_reg.intercept_

array([-36.94192021])

In [58]:
my_lin_reg.coef_

array([[ 4.36693293e-01],
       [ 9.43577803e-03],
       [-1.07322041e-01],
       [ 6.45065694e-01],
       [-3.97638942e-06],
       [-3.78654265e-03],
       [-4.21314378e-01],
       [-4.34513755e-01]])

In [59]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()

In [60]:
lin_reg.fit(housing.data,housing.target.reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [61]:
lin_reg.intercept_

array([-36.94192021])

In [62]:
lin_reg.coef_

array([[ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,
         6.45065694e-01, -3.97638942e-06, -3.78654265e-03,
        -4.21314378e-01, -4.34513755e-01]])

In [63]:
y_hat = my_lin_reg.predict(housing.data[:100])

In [64]:
from sklearn.metrics import mean_squared_error
mean_squared_error(housing.target[:100].reshape(-1,1),y_hat)

0.49589462618817143

In [65]:
y_hat_l = lin_reg.predict(housing.data[:100])
mean_squared_error(housing.target[:100].reshape(-1,1),y_hat_l)

0.4958946261989313