In [2]:
import numpy as np
a = np.array([i**2 for i in range(10)])
b = np.array([[12+i,5+i,7+i] for i in range (5)])

In [3]:
b

array([[12,  5,  7],
       [13,  6,  8],
       [14,  7,  9],
       [15,  8, 10],
       [16,  9, 11]])

In [4]:
b.shape

(5, 3)

In [32]:
a = np.random.np.random.randint(1,10, size=(4,5), dtype=np.int64)
a

array([[7, 7, 2, 9, 6],
       [8, 5, 9, 4, 5],
       [1, 9, 2, 2, 1],
       [4, 3, 4, 6, 4]], dtype=int64)

In [6]:
a[0].ndim

1

In [7]:
a[0,:]

array([26, 88, 20, 55, 55], dtype=int64)

In [8]:
a[0].reshape(-1,1)

array([[26],
       [88],
       [20],
       [55],
       [55]], dtype=int64)

In [9]:
a[2][2]

45

In [10]:
a[:,2:4]

array([[20, 55],
       [97, 73],
       [45, 65],
       [50, 74]], dtype=int64)

In [11]:
a[:,[1,3]][[0,2]]

array([[88, 55],
       [14, 65]], dtype=int64)

In [12]:
a = np.random.randn(4,5)
a

array([[-0.18002995,  0.54705448, -0.2918733 ,  0.59977241, -1.82586434],
       [ 1.70959622, -0.1460828 ,  0.4104288 , -1.39647333, -1.28149461],
       [-1.19376944, -0.38586939,  1.00774337,  1.00492779,  0.73606265],
       [-0.2701144 , -0.64669353,  1.56033375,  0.61751484, -0.73496019]])

In [13]:
a[np.random.permutation(len(a))]

array([[-1.19376944, -0.38586939,  1.00774337,  1.00492779,  0.73606265],
       [ 1.70959622, -0.1460828 ,  0.4104288 , -1.39647333, -1.28149461],
       [-0.2701144 , -0.64669353,  1.56033375,  0.61751484, -0.73496019],
       [-0.18002995,  0.54705448, -0.2918733 ,  0.59977241, -1.82586434]])

In [14]:
a = np.random.randint(10,100,(4,5))
a

array([[58, 28, 49, 88, 85],
       [27, 54, 23, 10, 49],
       [78, 69, 23, 53, 89],
       [91, 20, 41, 46, 68]])

In [15]:
a[[True,False,True,True]]

array([[58, 28, 49, 88, 85],
       [78, 69, 23, 53, 89],
       [91, 20, 41, 46, 68]])

In [16]:
b = np.array(['ram','sam','ram','jadu'])
b

array(['ram', 'sam', 'ram', 'jadu'], dtype='<U4')

In [17]:
a[b == 'ram']

array([[58, 28, 49, 88, 85],
       [78, 69, 23, 53, 89]])

In [18]:
b == 'ram'

array([ True, False,  True, False])

In [19]:
a

array([[58, 28, 49, 88, 85],
       [27, 54, 23, 10, 49],
       [78, 69, 23, 53, 89],
       [91, 20, 41, 46, 68]])

In [20]:
a+2*a

array([[174,  84, 147, 264, 255],
       [ 81, 162,  69,  30, 147],
       [234, 207,  69, 159, 267],
       [273,  60, 123, 138, 204]])

In [21]:
b = np.random.np.random.randint(10,100, size=(4,5), dtype=np.int32)
b

array([[25, 92, 54, 53, 75],
       [50, 81, 90, 13, 11],
       [24, 79, 57, 43, 60],
       [15, 19, 22, 48, 59]])

In [22]:
a.dot(b.T)

array([[17711, 11657, 15281, 11719],
       [11090,  8463,  9595,  5308],
       [19024, 13227, 16253, 10782],
       [13867, 11206, 12159,  8867]])

In [23]:
np.linalg.inv(a.dot(a.T))

array([[ 0.00038377,  0.00017484, -0.0002845 , -0.00018324],
       [ 0.00017484,  0.00156999, -0.00128273,  0.00040333],
       [-0.0002845 , -0.00128273,  0.001402  , -0.00055385],
       [-0.00018324,  0.00040333, -0.00055385,  0.00063282]])

# Solve a linear algebra

In [24]:
A = np.array([[3,2,-1],[2,-2,4],[-1,0.5,-1]])
A

array([[ 3. ,  2. , -1. ],
       [ 2. , -2. ,  4. ],
       [-1. ,  0.5, -1. ]])

In [25]:
B = np.array([1,-2,0])
B

array([ 1, -2,  0])

# Solve

In [26]:
X = np.linalg.solve(A,B)
X

array([ 1., -2., -2.])

# Check if the solution is correct

In [27]:
np.allclose(A.dot(X),B)

True

In [28]:
@np.vectorize
def factorial(n):
    return 1 if n==0 else n*factorial(n-1)

In [29]:
vect_fact = np.vectorize(factorial)

In [33]:
factorial(a)

array([[  5040,   5040,      2, 362880,    720],
       [ 40320,    120, 362880,     24,    120],
       [     1, 362880,      2,      2,      1],
       [    24,      6,     24,    720,     24]], dtype=int64)